version: "{build}"

clone_depth: 1
clone_folder: c:\gopath\src\github.com\docker\cli

environment:
  GOPATH: c:\gopath
  DEPVERSION: v0.5.0

install:
  - mkdir %GOPATH%\bin
  - curl -o %GOPATH%\bin\dep.exe https://github.com/golang/dep/releases/download/%DEPVERSION%/dep-windows-amd64
  - set PATH=%PATH%;%GOPATH%\bin
  - go version
  - go env

deploy: false

before_build:
  - ps: $env:VERSION = Get-Content VERSION
  - ps: $env:GITCOMMIT = git rev-parse --short HEAD
  - ps: $env:BUILDTIME = Get-Date  -Format o | foreach {$_ -replace "T", " "}

build_script:
  - ps: .\scripts\make.ps1 -Binary

test_script:
  - ps: .\scripts\make.ps1 -TestUnit
