version: "{build}"

clone_depth: 1
clone_folder: c:\gopath\src\github.com\docker\cli

environment:
  GOPATH: c:\gopath

install:
  - set PATH=c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%;
  - go version
  - go env

deploy: false

before_build:
  - ps: $env:VERSION = Get-Content VERSION
  - ps: $env:GITCOMMIT = git rev-parse --short HEAD
  - ps: $env:BUILDTIME = Get-Date  -Format o | foreach {$_ -replace "T", " "}

build_script:
  # - ps: .\scripts\make.ps1 -Binary -Noisy
  # - go build -v
  - cd cmd\docker
  - ps: go build -v -tags "autogen" -ldflags "-linkmode=internal -X github.com/docker/cli/cli.Version=18.09.0-dev -X github.com/docker/cli/cli.GitCommit=f61f560 -X ""github.com/docker/cli/cli.BuildTime=2018-11-13 14:55:34.2184579+00:00""" -o C:\gopath\src\github.com\docker\cli\build\docker.exe

# test_script:
  # - ps: .\scripts\make.ps1 -TestUnit
